apiVersion: v1
kind: Service
metadata:
  name: {{ include "cd-arch-helm-challenge.fullname" . }}
  labels:
    {{- include "cd-arch-helm-challenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30080        
  selector:
    {{- include "cd-arch-helm-challenge.selectorLabels" . | nindent 4 }}
